export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_OTP = 'AUTH_SET_OTP';
export const AUTH_MESSAGE= 'AUTH_MESSAGE';
export const AUTH_UNLOAD = 'AUTH_UNLOAD';
export const AUTH_REMOVE_OTP = 'AUTH_REMOVE_OTP';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_IS_RESET = 'AUTH_IS_RESET';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const AUTH_VERIFY_RESET_TOKEN = 'AUTH_VERIFY_RESET_TOKEN';


export const TRIP_MESSAGE = 'TRIP_MESSAGE';
export const TRIP_UNLOAD = 'TRIP_UNLOAD';
export const TRIP_SUCCESS = 'SEARCH_TRIP_SUCCESS';
export const TRIP_START = 'SEARCH_TRIP_START';
export const TRIP_FAILED = 'SEARCH_TRIP_FAILED';
export const TRIP_UPDATE_SEARCH = 'TRIP_UPDATE_SEARCH';
export const TRIP_GET_DETAILS = 'TRIP_GET_DETAILS';
export const BOOK_TRIP = 'BOOK_TRIP';
export const BOOK_TRIP_START = 'BOOK_TRIP_START';
export const BOOK_TRIP_FAILED = 'BOOK_TRIP_FAILED';
export const BOOK_TRIP_SUCCESS = 'BOOK_TRIP_SUCCESS';

export const USER_TRIP_START = 'USER_TRIP_START';
export const USER_TRIP_FAILED = 'USER_TRIP_FAILED';
export const USER_TRIP_SUCCESS = 'USER_TRIP_SUCCESS';

export const PROFILE_START = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
